package bot;

public enum UserState {
    CHARACTERISTIC_TYPE,
    GET_GENRE,
    BASE_COMMAND,
    END,
    GET_FILMS,
    REQUEST,
    SHOW_BLACK_LIST,
    SHOW_WISH_LIST,
    SHOW_VIEWED_LIST,
    ADD_BLACK_LIST,
    ADD_WISH_LIST,
    ADD_VIEWED_LIST
}

